SET(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_CXX_COMPILER "$ENV{MINGW_W64_BIN_DIR}/x86_64-w64-mingw32-g++.exe")
set(CMAKE_C_COMPILER "$ENV{MINGW_W64_BIN_DIR}/x86_64-w64-mingw32-gcc.exe")
set(CMAKE_AR "$ENV{MINGW_W64_BIN_DIR}/ar.exe" CACHE FILEPATH "Arhiver")
